<?php
/**
 * See LICENSE.md for license details.
 */
?>
<?php
    /* @var $this Dhl_OnlineRetoure_Block_Sales_Order_Info_Buttons_Return */
    $_order = $this->getOrder();
    $_returnUrl = $this->getReturnUrl($_order);
?>
<?php if ($_returnUrl): ?>
    <span class="separator">|</span>
    <a href="<?php echo $_returnUrl ?>" class="link-print"><?php echo $this->__('Return Order') ?></a>
<?php endif; ?>
