<?php
/**
 * See LICENSE.md for license details.
 */
?>
<?php /** @var Dhl_OnlineRetoure_Block_Customer_Address_Edit $this */ ?>
<div class="page-title">
    <h1><?php echo $this->escapeHtml($this->__('Check shipping address for DHL Online Return')) ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->escapeUrl($this->getSaveUrl()) ?>" method="post" id="form-validate">
    <div class="fieldset">
    <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->escapeHtml($this->__('Contact Information')) ?></h2>
        <ul class="form-list">
            <li class="fields">
                <?php echo $this->getNameBlockHtml() ?>
            </li>
            <li class="wide">
                <label for="company"><?php echo $this->escapeHtml($this->__('Company')) ?></label>
                <div class="input-box">
                    <input type="text" name="company" id="company"
                           title="<?php echo $this->escapeHtml($this->__('Company')) ?>"
                           value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>"
                           class="input-text <?php echo $this->helper('dhlonlineretoure/customer_address')->getAttributeValidationClass('company') ?>" />
                </div>
            </li>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->escapeHtml($this->__('Address')) ?></h2>
        <ul class="form-list">
        <?php $_streetValidationClass = $this->helper('dhlonlineretoure/customer_address')->getAttributeValidationClass('street'); ?>
            <li class="wide">
                <label for="street_1" class="required"><em>*</em><?php echo $this->escapeHtml($this->__('Street Address')) ?></label>
                <div class="input-box">
                    <input type="text" name="street[]" id="street_1"
                           class="input-text <?php echo $_streetValidationClass ?>"
                           value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>"
                           title="<?php echo $this->escapeHtml($this->__('Street Address')) ?>" />
                </div>
            </li>
        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
            <li class="wide">
                <div class="input-box">
                    <input type="text" name="street[]" id="street_<?php echo $_i ?>"
                           class="input-text <?php echo $_streetValidationClass ?>"
                           value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>"
                           title="<?php echo $this->escapeHtml($this->__('Street Address %s', $_i)) ?>" />
                </div>
            </li>
        <?php endfor; ?>
            <?php if ($this->helper('dhlonlineretoure/customer_address')->isVatAttributeVisible()) : ?>
            <li class="wide">
                <label for="vat_id"><?php echo $this->escapeHtml($this->__('VAT Number')) ?></label>
                <div class="input-box">
                    <input type="text" name="vat_id" id="vat_id"
                           value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>"
                           title="<?php echo $this->escapeHtml($this->__('VAT Number')) ?>"
                           class="input-text <?php echo $this->helper('dhlonlineretoure/customer_address')->getAttributeValidationClass('vat_id') ?>" />
                </div>
            </li>
            <?php endif; ?>
            <li class="fields">
                <div class="field">
                    <label for="city" class="required"><em>*</em><?php echo $this->escapeHtml($this->__('City')) ?></label>
                    <div class="input-box">
                        <input type="text" name="city" id="city"
                               value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"
                               title="<?php echo $this->escapeHtml($this->__('City')) ?>"
                               class="input-text <?php echo $this->helper('dhlonlineretoure/customer_address')->getAttributeValidationClass('city') ?>" />
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="zip" class="required"><em>*</em><?php echo $this->escapeHtml($this->__('Zip/Postal Code')) ?></label>
                    <div class="input-box">
                        <input type="text" name="postcode" id="zip"
                               value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
                               title="<?php echo $this->escapeHtml($this->__('Zip/Postal Code')) ?>"
                               class="input-text validate-zip-international <?php echo $this->helper('dhlonlineretoure/customer_address')->getAttributeValidationClass('postcode') ?>" />
                    </div>
                </div>
                <div class="field">
                    <label for="country" class="required"><em>*</em><?php echo $this->escapeHtml($this->__('Country')) ?></label>
                    <div class="input-box">
                        <?php echo $this->getCountryHtmlSelect() ?>
                    </div>
                </div>
            </li>
        </ul>
    </div>

    <?php echo $this->getChildHtml('dhlonlineretoure_return_items')?>

    <div class="buttons-set">
        <p class="required"><?php echo $this->escapeHtml($this->__('* Required Fields')) ?></p>
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->escapeHtml($this->__('Back')) ?></a></p>
        <?php if ($this->getRevocationPageUrl()): ?>
            <p class="back-link" style="margin-left: 10px;"><a href="<?php echo $this->escapeUrl($this->getRevocationPageUrl()) ?>"><?php echo $this->escapeHtml($this->__('Revocation')) ?></a></p>
        <?php endif; ?>
        <button type="submit" title="<?php echo $this->escapeHtml($this->__('Generate Return Form')) ?>" class="button"><span><span><?php echo $this->escapeHtml($this->__('Generate Return Form')) ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
