<?php /** @var Dhl_OnlineRetoure_Block_Sales_Order_Email_Retoure $this */ ?>
<?php $order = $this->getData('order'); ?>
<?php /** @var Dhl_OnlineRetoure_Helper_Validate $validateHelper */ ?>
<?php $validateHelper = Mage::helper("dhlonlineretoure/validate"); ?>

<?php
/*
 * If the block should be only visible for orders with shipments, add the check ...
 * true === $validateHelper->isOrderHasShipments($order)
 * ... to the following if-statement
 */
if (($order instanceof Mage_Sales_Model_Order && $validateHelper->isModuleFrontendEnabled($order)
    && $validateHelper->isReceiverIdAvailable($order)
    && Mage::getModel("dhlonlineretoure/config")->isAllowedShippingMethod($order->getShippingMethod(), $order->getStoreId()))
):
?>
    <div class="dhlonlineretoure_retoure" style="border-top:2px solid #EAEAEA;">
        <b><?php echo $validateHelper->__('DHL Online Return'); ?></b>
        <p>
            <?php
                echo $validateHelper->__(
                    'Create your <a href="%s">return label</a> online and deliver your parcel to a <a href="%s">nearby location</a>.',
                    $this->getReturnLinkWithHash(),
                    'http://standorte.deutschepost.de'
                );
            ?>
        </p>
    </div>
<?php endif; ?>
