<?php /** @var Dhl_OnlineRetoure_Block_Sales_Order_Email_Retoure $this */ ?>
<?php $order = $this->getData('order'); ?>
<?php /** @var Dhl_OnlineRetoure_Helper_Validate $validateHelper */ ?>
<?php $validateHelper = Mage::helper("dhlonlineretoure/validate"); ?>

<?php
/*
 * If the block should be only visible for orders with shipments, add the check ...
 * true === $validateHelper->isOrderHasShipments($order)
 * ... to the following if-statement
 */
if (($order instanceof Mage_Sales_Model_Order && $validateHelper->isModuleFrontendEnabled($order)
    && $validateHelper->isReceiverIdAvailable($order)
    && Mage::getModel("dhlonlineretoure/config")->isAllowedShippingMethod($order->getShippingMethod(), $order->getStoreId()))
):
?>
    <?php echo $this->getReturnLinkWithHash(); ?>
<?php endif; ?>
